### ISSUE TITLE
Исправить вывод текста в блоках цитаты

### ISSUE THREAD

**Issue by Magnumv44** [Magnumv44/template_magnum#12]
Попробовать добавить правило типа, при помощи CSS можно переносить непереносимые текстовые конструкции:
```css
.break-word {
        word-wrap: break-word;
}
```
