### ISSUE TITLE
Добавить кнопку "Наверх"

### ISSUE THREAD

**Issue by Magnumv44** [Magnumv44/template_magnum#5]
Сделать кнопку "Наверх" в двух вариантах:
1. Для ПК
2. Для смартфонов (такую как на xakep.ru)

**Comment by Magnumv44** [comment]
Прикрутить http://ruseller.com/lessons.php?rub=32&id=1714

**Comment by Magnumv44** [comment]
Вариант с сайта Попова не подошел =(

Можно попробовать поставить компонент который используется на официальном сайте Joomla или как минимум выдрать оттуда скрипт, картинку и стили.
Вот вариант: https://www.joomla.org/announcements/release-news/5641-joomla-3-4-6-released.html
``` css
<style type="text/css">
#scrollToTop {
	cursor: pointer;
	font-size: 0.9em;
	position: fixed;
	text-align: center;
	z-index: 9999;
	-webkit-transition: background-color 0.2s ease-in-out;
	-moz-transition: background-color 0.2s ease-in-out;
	-ms-transition: background-color 0.2s ease-in-out;
	-o-transition: background-color 0.2s ease-in-out;
	transition: background-color 0.2s ease-in-out;

	background: #1b63a2;
	color: #ffffff;
	border-radius: 0px;
	padding-left: 7px;
	padding-right: 7px;
	padding-top: 7px;
	padding-bottom: 7px;
	right: 10px; bottom: 10px;
}

#scrollToTop:hover {
	background: #1b63a2;
	color: #ffffff;
}

#scrollToTop > img {
	display: block;
	margin: 0 auto;
}
</style>
```
