### ISSUE TITLE
Оформление надписи пустых категорий

### ISSUE THREAD

**Issue by Magnumv44** [Magnumv44/template_magnum#7]
Сделать более приятный вывод надписи "В данной категории нет материалов." для категорий в которых еще ни одной новости.
Стили нужно прописать для класса "blog":
1. Выровнять по центру
2. Слегка увеличить текст (в зависимости от размера экрана)

**Comment by Magnumv44** [comment]
Проделано:
1. Выравнивание текста по центру;
2. Увеличен размер до 18 пикселей, выделено жирным;
3. Добавлена тень делающая надпись более выделяющейся.

**Comment by Magnumv44** [comment]
В стилях:

``` CSS
/*Стали для вывода информации об отсуствии конетента в категории*/
.span8 .blog p {
	margin-top: 1em;
	text-align: center;
	font: bold 18px Verdana;
	text-shadow: 1px 1px 1px silver, -1px 1px 1px silver;
}
```
Есть баг! Во всех категориях текст в теге <p> выделяется так же как и надпись, что в категории нет новостей.
Для устранения нужно этот тест либо заключить в отельный класс (а для этого нужно найти где именно его прописать), либо же абзацам контента жестко присвоить стили для текста (это как крайний вариант, лучше сделать по первому варианту).
